import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-50 dark:bg-black`}> 
        <div className="flex min-h-screen">
          <aside className="w-64 bg-white dark:bg-zinc-900 border-r border-zinc-200 dark:border-zinc-800 flex flex-col p-4">
            <nav className="flex flex-col gap-2">
              <a href="/dashboard" className="font-semibold text-lg hover:text-primary">Dashboard</a>
              <a href="/items" className="font-semibold text-lg hover:text-primary">Items</a>
              <a href="/watchlist" className="font-semibold text-lg hover:text-primary">Watchlist</a>
              <a href="/alerts" className="font-semibold text-lg hover:text-primary">Alerts</a>
              <a href="/settings" className="font-semibold text-lg hover:text-primary">Settings</a>
            </nav>
            <div className="mt-auto text-xs text-muted-foreground">NationsGlory Mocha</div>
          </aside>
          <main className="flex-1 flex flex-col">
            <header className="h-16 bg-white dark:bg-zinc-900 border-b border-zinc-200 dark:border-zinc-800 flex items-center px-6">
              <span className="font-bold text-xl">NG-Trader HDV Analyzer</span>
              <div className="ml-auto flex gap-2">
                {/* Placeholders pour actions/topbar */}
              </div>
            </header>
            <div className="flex-1 p-4 overflow-y-auto">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
